### PR TITLE
Region select

### PR DESCRIPTION
**Pull request by alan-wu**
Improve search and selection to support regions.
It also fixes a large number of issues of primitives with world transformation.
Greatly enhance performance when objects are selected and hovered.
Search index now uses a build-in UUID of objects.

### CODE REVIEW

**Review by Tehsurfer — APPROVED** [review]
Looks good! I like the new functions. Will be handy for when we link it to the sidebar

**Comment by Tehsurfer** [comment]
image

I think the indentation could be improved at some point, but I'm not really sure how yet

**Comment by alan-wu** [comment]
> image
> 
> I think the indentation could be improved at some point, but I'm not really sure how yet.
> 
> I think its totally fine for the moment

Can you elaborate please? Do you mean getting the text to be left-align? I will not worry too much about the autosuggest here as it is part of the demo and not the scaffoldvuer itself.

**Comment by Tehsurfer** [comment]
Oh is that just centered text? Yeah that is what I meant, I thought it was displaying hierchy

**Comment by alan-wu** [comment]
I have added the css to push the text to the left.

**Pull request merged**
